//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.13
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace BCD_SATINALMATALEP.Entities {
    
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepForm")]
    public class E_BCD_SATINALMATALEP_TalepFormEntity : FormEntity<E_BCD_SATINALMATALEP_TalepFormEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _NumberBox1;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _NumberBox2;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _NumberBox3;
        
        private E_BCD_SATINALMATALEP_TalepFormVREntity _VersionEntity;
        
        private RDEntityCollection<E_BCD_SATINALMATALEP_TalepFormRDEntity, E_BCD_SATINALMATALEP_TalepFormRDMLEntity> _RD;
        
        private RDCEntityCollection<E_BCD_SATINALMATALEP_TalepFormRDCEntity, E_BCD_SATINALMATALEP_TalepFormRDCMLEntity> _RDC;
        
        private SLEntityCollection<E_BCD_SATINALMATALEP_TalepFormSLEntity, E_BCD_SATINALMATALEP_TalepFormSLMLEntity> _SL;
        
        public E_BCD_SATINALMATALEP_TalepFormEntity() {
            this.VersionEntity = new E_BCD_SATINALMATALEP_TalepFormVREntity();
            this.RD = new RDEntityCollection<E_BCD_SATINALMATALEP_TalepFormRDEntity, E_BCD_SATINALMATALEP_TalepFormRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_BCD_SATINALMATALEP_TalepFormRDCEntity, E_BCD_SATINALMATALEP_TalepFormRDCMLEntity>();
            this.SL = new SLEntityCollection<E_BCD_SATINALMATALEP_TalepFormSLEntity, E_BCD_SATINALMATALEP_TalepFormSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="NumberBox1", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> NumberBox1 {
            get {
                return this._NumberBox1;
            }
            set {
                this._NumberBox1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="NumberBox2", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> NumberBox2 {
            get {
                return this._NumberBox2;
            }
            set {
                this._NumberBox2 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="NumberBox3", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> NumberBox3 {
            get {
                return this._NumberBox3;
            }
            set {
                this._NumberBox3 = value;
            }
        }
        
        public E_BCD_SATINALMATALEP_TalepFormVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_BCD_SATINALMATALEP_TalepFormRDEntity, E_BCD_SATINALMATALEP_TalepFormRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_BCD_SATINALMATALEP_TalepFormRDCEntity, E_BCD_SATINALMATALEP_TalepFormRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public SLEntityCollection<E_BCD_SATINALMATALEP_TalepFormSLEntity, E_BCD_SATINALMATALEP_TalepFormSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormSL")]
    public class E_BCD_SATINALMATALEP_TalepFormSLEntity : SLEntity<E_BCD_SATINALMATALEP_TalepFormSLEntity, E_BCD_SATINALMATALEP_TalepFormSLMLEntity> {
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormSLML")]
    public class E_BCD_SATINALMATALEP_TalepFormSLMLEntity : SLMLEntity<E_BCD_SATINALMATALEP_TalepFormSLMLEntity> {
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormVR")]
    public class E_BCD_SATINALMATALEP_TalepFormVREntity : VersionEntity<E_BCD_SATINALMATALEP_TalepFormVREntity> {
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormRDC")]
    public class E_BCD_SATINALMATALEP_TalepFormRDCEntity : RDCEntity<E_BCD_SATINALMATALEP_TalepFormRDCEntity, E_BCD_SATINALMATALEP_TalepFormRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormRDCML")]
    public class E_BCD_SATINALMATALEP_TalepFormRDCMLEntity : RDCMLEntity<E_BCD_SATINALMATALEP_TalepFormRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormRD")]
    public class E_BCD_SATINALMATALEP_TalepFormRDEntity : RDEntity<E_BCD_SATINALMATALEP_TalepFormRDEntity, E_BCD_SATINALMATALEP_TalepFormRDMLEntity> {
    }
    
    [TableOptions(TableName="E_BCD_SATINALMATALEP_TalepFormRDML")]
    public class E_BCD_SATINALMATALEP_TalepFormRDMLEntity : RDMLEntity<E_BCD_SATINALMATALEP_TalepFormRDMLEntity> {
    }
}




